version: '3.7'
services:
  lologen-binary:
    container_name: lologen-binary
    image: mdd13/lologen:binary
    build:
      context: ../
      dockerfile: ./binary/binary.dockerfile
    restart: on-failure
    command: [ "-f", "logfmt", "-l", "info", "-s", "stdout", "-t", "console", "-T", "2", "-c", "always"]

    # Driver variant
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push"
        loki-retries: "3"
        loki-pipeline-stages: |
          - json:
              expressions:
                level:
          - regex:
              expression: '(level|levelname|level_extracted|lvl|severity)=(?P<level>\w+)'
          - labels:
              level:

    # Scrape variant:
    # labels:
    #   name: "lologen"
